/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:a9f2aedf-7acb-45e4-ba0d-4025fbf0f4b6",
    "aws_cognito_region": "eu-west-2",
    "oauth": {},
    "aws_bots": "enable",
    "aws_bots_config": [
        {
            "name": "ScheduleAppointment_dev",
            "alias": "$LATEST",
            "region": "eu-west-2"
        },
        {
            "name": "ScheduleAppointment_dev",
            "alias": "$LATEST",
            "region": "eu-west-2"
        },
        {
            "name": "OrderFlowers_dev",
            "alias": "$LATEST",
            "region": "eu-west-2"
        }
    ]
};


export default awsmobile;
